"""
Nationwide demo coverage of Nigerian fuel stations.

These records **synthesise** approximate locations inside well-known
neighbourhoods/landmarks of major Nigerian cities so that the nearby-search
endpoint (PostGIS ``ST_DWithin`` / ``ST_Distance``) returns sensible results for
users across the country — not only in Lagos/FCT.

* **DEMO DATA — NOT VERIFIED.** Coordinates, addresses and station names here
  are illustrative seed values. They are **not** a verified directory of
  real-world businesses; do not rely on this catalogue for navigation,
  contact or commercial decisions.
* Every name carries a ``(Demo)`` suffix so the catalogue is clearly
  distinguishable from production-captured rows.
* Coverage is deliberately weighted to priority population centres listed in
  the feature brief, with secondary cities/towns included so that nearby
  searches work from anywhere a driver is likely to be.
* All coordinates fall inside the same generous Nigeria bounding box used by
  the test suite (lat 4.0–14.0 N, lon 2.5–15.0 E).

The :data:`NATIONWIDE_STATIONS` list is concatenated with the original 18
Lagos/FCT records by :mod:`.stations`.
"""

from __future__ import annotations

NATIONWIDE_STATIONS: list[dict] = [
    # =================================================================== #
    # NORTH-WEST / NORTH-CENTRAL (Kaduna, Kano, Katsina, Zaria, Sokoto,    #
    # FCT, Plateau, Nasarawa, Niger, Kwara, Kogi, Benue)                  #
    # =================================================================== #

    # ---- Kaduna (≥4 stations within 5 km of 10.5207, 7.4386) ----
    {
        "name": "NNPC Retail Kaduna Central (Demo)",
        "brand": "NNPC",
        "address": "Independence Way, Kaduna Central",
        "city": "Kaduna",
        "state": "Kaduna",
        "latitude": 10.5207,
        "longitude": 7.4386,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Kaduna North (Demo)",
        "brand": "TotalEnergies",
        "address": "Kaduna North, near Independence Way",
        "city": "Kaduna",
        "state": "Kaduna",
        "latitude": 10.5350,
        "longitude": 7.4386,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Conoil Kaduna South (Demo)",
        "brand": "Conoil",
        "address": "Kaduna South, Ahmadu Bello Way axis",
        "city": "Kaduna",
        "state": "Kaduna",
        "latitude": 10.5050,
        "longitude": 7.4386,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Mobil Ungwan Rimi (Demo)",
        "brand": "Mobil",
        "address": "Ungwan Rimi, Kaduna",
        "city": "Kaduna",
        "state": "Kaduna",
        "latitude": 10.5200,
        "longitude": 7.4450,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Oando Hayin Banki (Demo)",
        "brand": "Oando",
        "address": "Hayin Banki, Kaduna",
        "city": "Kaduna",
        "state": "Kaduna",
        "latitude": 10.5250,
        "longitude": 7.4200,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "MRS Oil Malali (Demo)",
        "brand": "MRS",
        "address": "Malali, Kaduna",
        "city": "Kaduna",
        "state": "Kaduna",
        "latitude": 10.5400,
        "longitude": 7.4580,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Bovas Tudun Wada (Demo)",
        "brand": "Bovas",
        "address": "Tudun Wada, Kaduna",
        "city": "Kaduna",
        "state": "Kaduna",
        "latitude": 10.5100,
        "longitude": 7.4300,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "NIPCO Sabon Tasha (Demo)",
        "brand": "NIPCO",
        "address": "Sabon Tasha, Kaduna",
        "city": "Kaduna",
        "state": "Kaduna",
        "latitude": 10.4850,
        "longitude": 7.4550,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Forte Oil Kakuri (Demo)",
        "brand": "Forte Oil",
        "address": "Kakuri, Kaduna South",
        "city": "Kaduna",
        "state": "Kaduna",
        "latitude": 10.4950,
        "longitude": 7.4100,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "AA Rano Kawo (Demo)",
        "brand": "AA Rano",
        "address": "Kawo, Kaduna North",
        "city": "Kaduna",
        "state": "Kaduna",
        "latitude": 10.5607,
        "longitude": 7.4386,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "AYM Shafa Command Junction (Demo)",
        "brand": "AYM Shafa",
        "address": "Command Junction, Kaduna",
        "city": "Kaduna",
        "state": "Kaduna",
        "latitude": 10.5150,
        "longitude": 7.4500,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Optima Energy Television (Demo)",
        "brand": "Optima",
        "address": "Television, Kaduna",
        "city": "Kaduna",
        "state": "Kaduna",
        "latitude": 10.4807,
        "longitude": 7.4300,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },

    # ---- Zaria ----
    {
        "name": "NNPC Retail Zaria Sabon Gari (Demo)",
        "brand": "NNPC",
        "address": "Sabon Gari, Zaria",
        "city": "Zaria",
        "state": "Kaduna",
        "latitude": 11.0851,
        "longitude": 7.7197,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "TotalEnergies Zaria Tudun Wada (Demo)",
        "brand": "TotalEnergies",
        "address": "Tudun Wada, Zaria",
        "city": "Zaria",
        "state": "Kaduna",
        "latitude": 11.1230,
        "longitude": 7.7350,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Mobil Zaria GRA (Demo)",
        "brand": "Mobil",
        "address": "GRA, Zaria",
        "city": "Zaria",
        "state": "Kaduna",
        "latitude": 11.0700,
        "longitude": 7.7050,
        "fuel_types": ["PMS", "AGO", "LPG"],
    },

    # ---- Kano ----
    {
        "name": "NNPC Retail Kano City (Demo)",
        "brand": "NNPC",
        "address": "Kano Municipal, Kano",
        "city": "Kano",
        "state": "Kano",
        "latitude": 12.0022,
        "longitude": 8.5920,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Kano Nassarawa GRA (Demo)",
        "brand": "TotalEnergies",
        "address": "Nassarawa GRA, Kano",
        "city": "Kano",
        "state": "Kano",
        "latitude": 12.0300,
        "longitude": 8.5400,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Kano Sabon Gari (Demo)",
        "brand": "Mobil",
        "address": "Sabon Gari, Kano",
        "city": "Kano",
        "state": "Kano",
        "latitude": 12.0100,
        "longitude": 8.5200,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Kano Tarauni (Demo)",
        "brand": "Conoil",
        "address": "Tarauni, Kano",
        "city": "Kano",
        "state": "Kano",
        "latitude": 12.0450,
        "longitude": 8.5350,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Oando Kano Fagge (Demo)",
        "brand": "Oando",
        "address": "Fagge, Kano",
        "city": "Kano",
        "state": "Kano",
        "latitude": 11.9900,
        "longitude": 8.5150,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Katsina ----
    {
        "name": "NNPC Retail Katsina Central (Demo)",
        "brand": "NNPC",
        "address": "Katsina Central, Katsina",
        "city": "Katsina",
        "state": "Katsina",
        "latitude": 12.9908,
        "longitude": 7.6017,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "TotalEnergies Katsina GRA (Demo)",
        "brand": "TotalEnergies",
        "address": "GRA, Katsina",
        "city": "Katsina",
        "state": "Katsina",
        "latitude": 13.0000,
        "longitude": 7.6200,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Mobil Katsina Yahaya Madaki (Demo)",
        "brand": "Mobil",
        "address": "Yahaya Madaki Way, Katsina",
        "city": "Katsina",
        "state": "Katsina",
        "latitude": 12.9800,
        "longitude": 7.6100,
        "fuel_types": ["PMS", "AGO", "LPG"],
    },

    # ---- Sokoto ----
    {
        "name": "NNPC Retail Sokoto Central (Demo)",
        "brand": "NNPC",
        "address": "Sokoto Central, Sokoto",
        "city": "Sokoto",
        "state": "Sokoto",
        "latitude": 13.0059,
        "longitude": 5.2476,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "TotalEnergies Sokoto Runjin Sambo (Demo)",
        "brand": "TotalEnergies",
        "address": "Runjin Sambo, Sokoto",
        "city": "Sokoto",
        "state": "Sokoto",
        "latitude": 13.0300,
        "longitude": 5.2200,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Sokoto Mabera (Demo)",
        "brand": "Conoil",
        "address": "Mabera, Sokoto",
        "city": "Sokoto",
        "state": "Sokoto",
        "latitude": 12.9850,
        "longitude": 5.2700,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Kebbi (Argungu) ----
    {
        "name": "NNPC Retail Birnin Kebbi (Demo)",
        "brand": "NNPC",
        "address": "Birnin Kebbi Central",
        "city": "Birnin Kebbi",
        "state": "Kebbi",
        "latitude": 12.4531,
        "longitude": 4.1975,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "TotalEnergies Argungu (Demo)",
        "brand": "TotalEnergies",
        "address": "Argungu Town",
        "city": "Argungu",
        "state": "Kebbi",
        "latitude": 12.7449,
        "longitude": 4.5251,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Zamfara (Gusau) ----
    {
        "name": "NNPC Retail Gusau (Demo)",
        "brand": "NNPC",
        "address": "Gusau Central, Gusau",
        "city": "Gusau",
        "state": "Zamfara",
        "latitude": 12.1700,
        "longitude": 6.6599,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "TotalEnergies Gusau Bye-Pass (Demo)",
        "brand": "TotalEnergies",
        "address": "Gusau Bye-Pass",
        "city": "Gusau",
        "state": "Zamfara",
        "latitude": 12.1850,
        "longitude": 6.6700,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Jigawa (Dutse) ----
    {
        "name": "NNPC Retail Dutse (Demo)",
        "brand": "NNPC",
        "address": "Dutse, Jigawa",
        "city": "Dutse",
        "state": "Jigawa",
        "latitude": 11.7564,
        "longitude": 9.3384,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Hadejia (Demo)",
        "brand": "Mobil",
        "address": "Hadejia, Jigawa",
        "city": "Hadejia",
        "state": "Jigawa",
        "latitude": 12.4536,
        "longitude": 10.0414,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- FCT (Abuja) — additional demo coverage beyond the original 3 ----
    {
        "name": "NNPC Retail Utako (Demo)",
        "brand": "NNPC",
        "address": "Utako District, Abuja",
        "city": "Utako",
        "state": "FCT",
        "latitude": 9.0700,
        "longitude": 7.4380,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "TotalEnergies Jabi (Demo)",
        "brand": "TotalEnergies",
        "address": "Jabi Lake axis, Abuja",
        "city": "Jabi",
        "state": "FCT",
        "latitude": 9.0620,
        "longitude": 7.4250,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Wuse Zone 5 (Demo)",
        "brand": "Mobil",
        "address": "Wuse Zone 5, Abuja",
        "city": "Wuse Zone 5",
        "state": "FCT",
        "latitude": 9.0640,
        "longitude": 7.4620,
        "fuel_types": ["PMS", "AGO", "DPK", "CNG"],
    },
    {
        "name": "Conoil Apo (Demo)",
        "brand": "Conoil",
        "address": "Apo Legislative Quarters, Abuja",
        "city": "Apo",
        "state": "FCT",
        "latitude": 9.0050,
        "longitude": 7.4900,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Oando Gwarinpa (Demo)",
        "brand": "Oando",
        "address": "Gwarinpa Estate, Abuja",
        "city": "Gwarinpa",
        "state": "FCT",
        "latitude": 9.1050,
        "longitude": 7.4100,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "MRS Oil Asokoro (Demo)",
        "brand": "MRS",
        "address": "Asokoro District, Abuja",
        "city": "Asokoro",
        "state": "FCT",
        "latitude": 9.0410,
        "longitude": 7.5250,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "NNPC Retail Kubwa (Demo)",
        "brand": "NNPC",
        "address": "Kubwa Expressway, Abuja",
        "city": "Kubwa",
        "state": "FCT",
        "latitude": 9.1500,
        "longitude": 7.3300,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "NIPCO Nyanya (Demo)",
        "brand": "NIPCO",
        "address": "Nyanya-Karu Expressway, Abuja",
        "city": "Nyanya",
        "state": "FCT",
        "latitude": 9.0240,
        "longitude": 7.5800,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },

    # ---- Plateau (Jos) ----
    {
        "name": "NNPC Retail Jos Township (Demo)",
        "brand": "NNPC",
        "address": "Jos Township, Plateau",
        "city": "Jos",
        "state": "Plateau",
        "latitude": 9.8965,
        "longitude": 8.8583,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Jos Rayfield (Demo)",
        "brand": "TotalEnergies",
        "address": "Rayfield, Jos",
        "city": "Jos",
        "state": "Plateau",
        "latitude": 9.8700,
        "longitude": 8.8900,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Jos Bukuru (Demo)",
        "brand": "Mobil",
        "address": "Bukuru, Jos",
        "city": "Bukuru",
        "state": "Plateau",
        "latitude": 9.7950,
        "longitude": 8.8800,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Jos Terminus (Demo)",
        "brand": "Conoil",
        "address": "Terminus Market, Jos",
        "city": "Jos",
        "state": "Plateau",
        "latitude": 9.9100,
        "longitude": 8.8900,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Nasarawa (Lafia, Keffi, Akwanga) ----
    {
        "name": "NNPC Retail Lafia (Demo)",
        "brand": "NNPC",
        "address": "Lafia, Nasarawa",
        "city": "Lafia",
        "state": "Nasarawa",
        "latitude": 8.4938,
        "longitude": 8.5154,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "TotalEnergies Keffi (Demo)",
        "brand": "TotalEnergies",
        "address": "Keffi, Nasarawa",
        "city": "Keffi",
        "state": "Nasarawa",
        "latitude": 8.8485,
        "longitude": 7.8733,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Akwanga (Demo)",
        "brand": "Mobil",
        "address": "Akwanga, Nasarawa",
        "city": "Akwanga",
        "state": "Nasarawa",
        "latitude": 8.9100,
        "longitude": 8.4067,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "NNPC Retail Mararaba (Demo)",
        "brand": "NNPC",
        "address": "Mararaba, Nasarawa",
        "city": "Mararaba",
        "state": "Nasarawa",
        "latitude": 8.9690,
        "longitude": 7.6360,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },

    # ---- Niger (Minna, Bida, Suleja) ----
    {
        "name": "NNPC Retail Minna Central (Demo)",
        "brand": "NNPC",
        "address": "Minna Central, Niger",
        "city": "Minna",
        "state": "Niger",
        "latitude": 9.5836,
        "longitude": 6.5463,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "TotalEnergies Minna Bosso (Demo)",
        "brand": "TotalEnergies",
        "address": "Bosso, Minna",
        "city": "Minna",
        "state": "Niger",
        "latitude": 9.6100,
        "longitude": 6.5300,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Mobil Bida (Demo)",
        "brand": "Mobil",
        "address": "Bida, Niger",
        "city": "Bida",
        "state": "Niger",
        "latitude": 9.0804,
        "longitude": 6.0099,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Suleja (Demo)",
        "brand": "Conoil",
        "address": "Suleja, Niger",
        "city": "Suleja",
        "state": "Niger",
        "latitude": 9.1806,
        "longitude": 7.1800,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Oando Kontagora (Demo)",
        "brand": "Oando",
        "address": "Kontagora, Niger",
        "city": "Kontagora",
        "state": "Niger",
        "latitude": 10.4031,
        "longitude": 5.4698,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Kwara (Ilorin) ----
    {
        "name": "NNPC Retail Ilorin GRA (Demo)",
        "brand": "NNPC",
        "address": "GRA, Ilorin",
        "city": "Ilorin",
        "state": "Kwara",
        "latitude": 8.4966,
        "longitude": 4.5420,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Ilorin Offa Road (Demo)",
        "brand": "TotalEnergies",
        "address": "Offa Road, Ilorin",
        "city": "Ilorin",
        "state": "Kwara",
        "latitude": 8.4850,
        "longitude": 4.5700,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Ilorin Taiwo Road (Demo)",
        "brand": "Mobil",
        "address": "Taiwo Road, Ilorin",
        "city": "Ilorin",
        "state": "Kwara",
        "latitude": 8.4790,
        "longitude": 4.5500,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Ilorin Saw-Mill (Demo)",
        "brand": "Conoil",
        "address": "Saw-Mill, Ilorin",
        "city": "Ilorin",
        "state": "Kwara",
        "latitude": 8.5150,
        "longitude": 4.5350,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Kogi (Lokoja, Okene) ----
    {
        "name": "NNPC Retail Lokoja (Demo)",
        "brand": "NNPC",
        "address": "Lokoja, Kogi",
        "city": "Lokoja",
        "state": "Kogi",
        "latitude": 7.8024,
        "longitude": 6.7440,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "TotalEnergies Okene (Demo)",
        "brand": "TotalEnergies",
        "address": "Okene, Kogi",
        "city": "Okene",
        "state": "Kogi",
        "latitude": 7.5506,
        "longitude": 6.2350,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Mobil Idah (Demo)",
        "brand": "Mobil",
        "address": "Idah, Kogi",
        "city": "Idah",
        "state": "Kogi",
        "latitude": 7.0833,
        "longitude": 6.7500,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Benue (Makurdi, Gboko) ----
    {
        "name": "NNPC Retail Makurdi High-Level (Demo)",
        "brand": "NNPC",
        "address": "High-Level, Makurdi",
        "city": "Makurdi",
        "state": "Benue",
        "latitude": 7.7322,
        "longitude": 8.5391,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Makurdi Wurukum (Demo)",
        "brand": "TotalEnergies",
        "address": "Wurukum, Makurdi",
        "city": "Makurdi",
        "state": "Benue",
        "latitude": 7.7150,
        "longitude": 8.5500,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Gboko (Demo)",
        "brand": "Mobil",
        "address": "Gboko, Benue",
        "city": "Gboko",
        "state": "Benue",
        "latitude": 7.3167,
        "longitude": 9.0000,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Otukpo (Demo)",
        "brand": "Conoil",
        "address": "Otukpo, Benue",
        "city": "Otukpo",
        "state": "Benue",
        "latitude": 7.1930,
        "longitude": 8.1550,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # =================================================================== #
    # NORTH-EAST (Borno, Yobe, Adamawa, Bauchi, Gombe, Taraba)            #
    # =================================================================== #

    # ---- Borno (Maiduguri) ----
    {
        "name": "NNPC Retail Maiduguri Monday Market (Demo)",
        "brand": "NNPC",
        "address": "Monday Market, Maiduguri",
        "city": "Maiduguri",
        "state": "Borno",
        "latitude": 11.8311,
        "longitude": 13.1510,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Maiduguri Gamboru (Demo)",
        "brand": "TotalEnergies",
        "address": "Gamboru, Maiduguri",
        "city": "Maiduguri",
        "state": "Borno",
        "latitude": 11.8450,
        "longitude": 13.1400,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Maiduguri Baga Road (Demo)",
        "brand": "Mobil",
        "address": "Baga Road, Maiduguri",
        "city": "Maiduguri",
        "state": "Borno",
        "latitude": 11.8200,
        "longitude": 13.1700,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Maiduguri Biu Road (Demo)",
        "brand": "Conoil",
        "address": "Biu Road, Maiduguri",
        "city": "Maiduguri",
        "state": "Borno",
        "latitude": 11.8100,
        "longitude": 13.1350,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Yobe (Damaturu, Potiskum) ----
    {
        "name": "NNPC Retail Damaturu (Demo)",
        "brand": "NNPC",
        "address": "Damaturu, Yobe",
        "city": "Damaturu",
        "state": "Yobe",
        "latitude": 11.7470,
        "longitude": 11.9608,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "TotalEnergies Potiskum (Demo)",
        "brand": "TotalEnergies",
        "address": "Potiskum, Yobe",
        "city": "Potiskum",
        "state": "Yobe",
        "latitude": 11.7097,
        "longitude": 11.0769,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Adamawa (Yola, Mubi) ----
    {
        "name": "NNPC Retail Yola Jimeta (Demo)",
        "brand": "NNPC",
        "address": "Jimeta, Yola",
        "city": "Yola",
        "state": "Adamawa",
        "latitude": 9.2167,
        "longitude": 12.4833,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Yola GRA (Demo)",
        "brand": "TotalEnergies",
        "address": "GRA, Yola",
        "city": "Yola",
        "state": "Adamawa",
        "latitude": 9.2300,
        "longitude": 12.4500,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Mubi (Demo)",
        "brand": "Mobil",
        "address": "Mubi, Adamawa",
        "city": "Mubi",
        "state": "Adamawa",
        "latitude": 10.2667,
        "longitude": 13.2667,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Bauchi ----
    {
        "name": "NNPC Retail Bauchi Central (Demo)",
        "brand": "NNPC",
        "address": "Bauchi Central, Bauchi",
        "city": "Bauchi",
        "state": "Bauchi",
        "latitude": 10.3158,
        "longitude": 9.8442,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Bauchi GRA (Demo)",
        "brand": "TotalEnergies",
        "address": "GRA, Bauchi",
        "city": "Bauchi",
        "state": "Bauchi",
        "latitude": 10.3050,
        "longitude": 9.8600,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Azare (Demo)",
        "brand": "Mobil",
        "address": "Azare, Bauchi",
        "city": "Azare",
        "state": "Bauchi",
        "latitude": 11.6740,
        "longitude": 10.1900,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Gombe ----
    {
        "name": "NNPC Retail Gombe Central (Demo)",
        "brand": "NNPC",
        "address": "Gombe Central, Gombe",
        "city": "Gombe",
        "state": "Gombe",
        "latitude": 10.2897,
        "longitude": 11.1673,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "TotalEnergies Gombe Pantami (Demo)",
        "brand": "TotalEnergies",
        "address": "Pantami, Gombe",
        "city": "Gombe",
        "state": "Gombe",
        "latitude": 10.3000,
        "longitude": 11.1500,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Taraba (Jalingo) ----
    {
        "name": "NNPC Retail Jalingo (Demo)",
        "brand": "NNPC",
        "address": "Jalingo, Taraba",
        "city": "Jalingo",
        "state": "Taraba",
        "latitude": 8.8937,
        "longitude": 11.3596,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "TotalEnergies Wukari (Demo)",
        "brand": "TotalEnergies",
        "address": "Wukari, Taraba",
        "city": "Wukari",
        "state": "Taraba",
        "latitude": 7.8714,
        "longitude": 9.7778,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # =================================================================== #
    # SOUTH-WEST (Oyo, Ogun, Ondo, Osun, Ekiti) — Lagos coverage is the   #
    # original 15 above.                                                  #
    # =================================================================== #

    # ---- Oyo (Ibadan) ----
    {
        "name": "NNPC Retail Ibadan Bodija (Demo)",
        "brand": "NNPC",
        "address": "Bodija, Ibadan",
        "city": "Ibadan",
        "state": "Oyo",
        "latitude": 7.4351,
        "longitude": 3.9116,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Ibadan Apata (Demo)",
        "brand": "TotalEnergies",
        "address": "Apata, Ibadan",
        "city": "Ibadan",
        "state": "Oyo",
        "latitude": 7.3950,
        "longitude": 3.8700,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Ibadan Ring Road (Demo)",
        "brand": "Mobil",
        "address": "Ring Road, Ibadan",
        "city": "Ibadan",
        "state": "Oyo",
        "latitude": 7.3780,
        "longitude": 3.9460,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Ibadan Akobo (Demo)",
        "brand": "Conoil",
        "address": "Akobo, Ibadan",
        "city": "Ibadan",
        "state": "Oyo",
        "latitude": 7.4250,
        "longitude": 3.9350,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Oando Ibadan Iwo Road (Demo)",
        "brand": "Oando",
        "address": "Iwo Road, Ibadan",
        "city": "Ibadan",
        "state": "Oyo",
        "latitude": 7.3580,
        "longitude": 3.8800,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "MRS Oil Ibadan Samonda (Demo)",
        "brand": "MRS",
        "address": "Samonda, Ibadan",
        "city": "Ibadan",
        "state": "Oyo",
        "latitude": 7.4470,
        "longitude": 3.8970,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "NNPC Retail Ogbomosho (Demo)",
        "brand": "NNPC",
        "address": "Ogbomosho, Oyo",
        "city": "Ogbomosho",
        "state": "Oyo",
        "latitude": 8.1333,
        "longitude": 4.2500,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "TotalEnergies Oyo (Demo)",
        "brand": "TotalEnergies",
        "address": "Oyo Town, Oyo",
        "city": "Oyo",
        "state": "Oyo",
        "latitude": 7.8500,
        "longitude": 3.9333,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Ogun (Abeokuta, Ijebu-Ode, Sagamu) ----
    {
        "name": "NNPC Retail Abeokuta Ibara (Demo)",
        "brand": "NNPC",
        "address": "Ibara, Abeokuta",
        "city": "Abeokuta",
        "state": "Ogun",
        "latitude": 7.1608,
        "longitude": 3.3481,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Abeokuta Kuto (Demo)",
        "brand": "TotalEnergies",
        "address": "Kuto, Abeokuta",
        "city": "Abeokuta",
        "state": "Ogun",
        "latitude": 7.1450,
        "longitude": 3.3450,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Abeokuta Sapon (Demo)",
        "brand": "Mobil",
        "address": "Sapon, Abeokuta",
        "city": "Abeokuta",
        "state": "Ogun",
        "latitude": 7.1800,
        "longitude": 3.3700,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Ijebu-Ode (Demo)",
        "brand": "Conoil",
        "address": "Ijebu-Ode, Ogun",
        "city": "Ijebu-Ode",
        "state": "Ogun",
        "latitude": 6.8200,
        "longitude": 3.9200,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Oando Sagamu (Demo)",
        "brand": "Oando",
        "address": "Sagamu, Ogun",
        "city": "Sagamu",
        "state": "Ogun",
        "latitude": 6.8411,
        "longitude": 3.6453,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },

    # ---- Ondo (Akure, Ondo Town, Owo) ----
    {
        "name": "NNPC Retail Akure Oba-Ile (Demo)",
        "brand": "NNPC",
        "address": "Oba-Ile, Akure",
        "city": "Akure",
        "state": "Ondo",
        "latitude": 7.2571,
        "longitude": 5.2058,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Akure Oke-Aro (Demo)",
        "brand": "TotalEnergies",
        "address": "Oke-Aro, Akure",
        "city": "Akure",
        "state": "Ondo",
        "latitude": 7.2500,
        "longitude": 5.1950,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Ondo Town (Demo)",
        "brand": "Mobil",
        "address": "Ondo Town, Ondo",
        "city": "Ondo",
        "state": "Ondo",
        "latitude": 7.0932,
        "longitude": 4.8353,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Owo (Demo)",
        "brand": "Conoil",
        "address": "Owo, Ondo",
        "city": "Owo",
        "state": "Ondo",
        "latitude": 7.1960,
        "longitude": 5.5866,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Osun (Osogbo, Ife, Ilesa) ----
    {
        "name": "NNPC Retail Osogbo (Demo)",
        "brand": "NNPC",
        "address": "Osogbo, Osun",
        "city": "Osogbo",
        "state": "Osun",
        "latitude": 7.7827,
        "longitude": 4.5418,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Osogbo Old Garage (Demo)",
        "brand": "TotalEnergies",
        "address": "Old Garage, Osogbo",
        "city": "Osogbo",
        "state": "Osun",
        "latitude": 7.7700,
        "longitude": 4.5550,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Ife (Demo)",
        "brand": "Mobil",
        "address": "Ile-Ife, Osun",
        "city": "Ile-Ife",
        "state": "Osun",
        "latitude": 7.4667,
        "longitude": 4.5500,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Ilesa (Demo)",
        "brand": "Conoil",
        "address": "Ilesa, Osun",
        "city": "Ilesa",
        "state": "Osun",
        "latitude": 7.6167,
        "longitude": 4.7333,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Ekiti (Ado-Ekiti) ----
    {
        "name": "NNPC Retail Ado-Ekiti (Demo)",
        "brand": "NNPC",
        "address": "Ado-Ekiti, Ekiti",
        "city": "Ado-Ekiti",
        "state": "Ekiti",
        "latitude": 7.6210,
        "longitude": 5.2214,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Ado-Ekiti Fajuyi (Demo)",
        "brand": "TotalEnergies",
        "address": "Fajuyi, Ado-Ekiti",
        "city": "Ado-Ekiti",
        "state": "Ekiti",
        "latitude": 7.6100,
        "longitude": 5.2300,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Ikere-Ekiti (Demo)",
        "brand": "Mobil",
        "address": "Ikere-Ekiti, Ekiti",
        "city": "Ikere-Ekiti",
        "state": "Ekiti",
        "latitude": 7.4910,
        "longitude": 5.2300,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # =================================================================== #
    # SOUTH-EAST (Enugu, Anambra, Imo, Abia, Ebonyi)                     #
    # =================================================================== #

    # ---- Enugu ----
    {
        "name": "NNPC Retail Enugu GRA (Demo)",
        "brand": "NNPC",
        "address": "GRA, Enugu",
        "city": "Enugu",
        "state": "Enugu",
        "latitude": 6.4584,
        "longitude": 7.5464,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Enugu Ogui (Demo)",
        "brand": "TotalEnergies",
        "address": "Ogui, Enugu",
        "city": "Enugu",
        "state": "Enugu",
        "latitude": 6.4400,
        "longitude": 7.5100,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Enugu New Haven (Demo)",
        "brand": "Mobil",
        "address": "New Haven, Enugu",
        "city": "Enugu",
        "state": "Enugu",
        "latitude": 6.4700,
        "longitude": 7.5200,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Enugu Trans-Ekulu (Demo)",
        "brand": "Conoil",
        "address": "Trans-Ekulu, Enugu",
        "city": "Enugu",
        "state": "Enugu",
        "latitude": 6.4750,
        "longitude": 7.5650,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Oando Enugu Uwani (Demo)",
        "brand": "Oando",
        "address": "Uwani, Enugu",
        "city": "Enugu",
        "state": "Enugu",
        "latitude": 6.4250,
        "longitude": 7.4900,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "NNPC Retail Nsukka (Demo)",
        "brand": "NNPC",
        "address": "Nsukka, Enugu",
        "city": "Nsukka",
        "state": "Enugu",
        "latitude": 6.8570,
        "longitude": 7.3950,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Anambra (Onitsha, Awka, Nnewi) ----
    {
        "name": "NNPC Retail Onitsha Main Market (Demo)",
        "brand": "NNPC",
        "address": "Main Market, Onitsha",
        "city": "Onitsha",
        "state": "Anambra",
        "latitude": 6.1667,
        "longitude": 6.7833,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Onitsha Oseokwuku (Demo)",
        "brand": "TotalEnergies",
        "address": "Oseokwuku, Onitsha",
        "city": "Onitsha",
        "state": "Anambra",
        "latitude": 6.1500,
        "longitude": 6.8000,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Onitsha Upper Iweka (Demo)",
        "brand": "Mobil",
        "address": "Upper Iweka, Onitsha",
        "city": "Onitsha",
        "state": "Anambra",
        "latitude": 6.1800,
        "longitude": 6.7600,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Awka (Demo)",
        "brand": "Conoil",
        "address": "Awka, Anambra",
        "city": "Awka",
        "state": "Anambra",
        "latitude": 6.2104,
        "longitude": 7.0698,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "NNPC Retail Nnewi (Demo)",
        "brand": "NNPC",
        "address": "Nnewi, Anambra",
        "city": "Nnewi",
        "state": "Anambra",
        "latitude": 6.0193,
        "longitude": 6.9140,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "TotalEnergies Ekwulobia (Demo)",
        "brand": "TotalEnergies",
        "address": "Ekwulobia, Anambra",
        "city": "Ekwulobia",
        "state": "Anambra",
        "latitude": 6.0278,
        "longitude": 7.0810,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Imo (Owerri) ----
    {
        "name": "NNPC Retail Owerri Wetheral (Demo)",
        "brand": "NNPC",
        "address": "Wetheral Road, Owerri",
        "city": "Owerri",
        "state": "Imo",
        "latitude": 5.4840,
        "longitude": 7.0351,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Owerri Egbu (Demo)",
        "brand": "TotalEnergies",
        "address": "Egbu Road, Owerri",
        "city": "Owerri",
        "state": "Imo",
        "latitude": 5.4700,
        "longitude": 7.0500,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Owerri Relief Market (Demo)",
        "brand": "Mobil",
        "address": "Relief Market, Owerri",
        "city": "Owerri",
        "state": "Imo",
        "latitude": 5.4900,
        "longitude": 7.0200,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Owerri Orji (Demo)",
        "brand": "Conoil",
        "address": "Orji, Owerri",
        "city": "Owerri",
        "state": "Imo",
        "latitude": 5.5050,
        "longitude": 7.0600,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Oando Orlu (Demo)",
        "brand": "Oando",
        "address": "Orlu, Imo",
        "city": "Orlu",
        "state": "Imo",
        "latitude": 5.7950,
        "longitude": 7.0350,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Abia (Aba, Umuahia) ----
    {
        "name": "NNPC Retail Aba Eziukwu (Demo)",
        "brand": "NNPC",
        "address": "Eziukwu Market, Aba",
        "city": "Aba",
        "state": "Abia",
        "latitude": 5.1167,
        "longitude": 7.3667,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Aba Cemetery Market (Demo)",
        "brand": "TotalEnergies",
        "address": "Cemetery Market, Aba",
        "city": "Aba",
        "state": "Abia",
        "latitude": 5.1000,
        "longitude": 7.3700,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Aba Owerri Road (Demo)",
        "brand": "Mobil",
        "address": "Owerri Road, Aba",
        "city": "Aba",
        "state": "Abia",
        "latitude": 5.1300,
        "longitude": 7.3500,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Umuahia (Demo)",
        "brand": "Conoil",
        "address": "Umuahia, Abia",
        "city": "Umuahia",
        "state": "Abia",
        "latitude": 5.5264,
        "longitude": 7.4900,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Oando Umuahia Ibeku (Demo)",
        "brand": "Oando",
        "address": "Ibeku, Umuahia",
        "city": "Umuahia",
        "state": "Abia",
        "latitude": 5.5400,
        "longitude": 7.4800,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Ebonyi (Abakaliki) ----
    {
        "name": "NNPC Retail Abakaliki (Demo)",
        "brand": "NNPC",
        "address": "Abakaliki, Ebonyi",
        "city": "Abakaliki",
        "state": "Ebonyi",
        "latitude": 6.3249,
        "longitude": 8.1137,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "TotalEnergies Afikpo (Demo)",
        "brand": "TotalEnergies",
        "address": "Afikpo, Ebonyi",
        "city": "Afikpo",
        "state": "Ebonyi",
        "latitude": 5.8950,
        "longitude": 7.9333,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # =================================================================== #
    # SOUTH-SOUTH (Rivers, Bayelsa, Delta, Edo, Cross River, Akwa Ibom)  #
    # =================================================================== #

    # ---- Rivers (Port Harcourt) ----
    {
        "name": "NNPC Retail Port Harcourt GRA (Demo)",
        "brand": "NNPC",
        "address": "Old GRA, Port Harcourt",
        "city": "Port Harcourt",
        "state": "Rivers",
        "latitude": 4.7796,
        "longitude": 7.0136,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Port Harcourt Trans-Amadi (Demo)",
        "brand": "TotalEnergies",
        "address": "Trans-Amadi, Port Harcourt",
        "city": "Port Harcourt",
        "state": "Rivers",
        "latitude": 4.7900,
        "longitude": 7.0450,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Port Harcourt Aba Road (Demo)",
        "brand": "Mobil",
        "address": "Aba Road, Port Harcourt",
        "city": "Port Harcourt",
        "state": "Rivers",
        "latitude": 4.8100,
        "longitude": 7.0000,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Port Harcourt Mile 3 (Demo)",
        "brand": "Conoil",
        "address": "Mile 3, Port Harcourt",
        "city": "Port Harcourt",
        "state": "Rivers",
        "latitude": 4.7700,
        "longitude": 6.9950,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Oando Port Harcourt Rukpokwu (Demo)",
        "brand": "Oando",
        "address": "Rukpokwu, Port Harcourt",
        "city": "Port Harcourt",
        "state": "Rivers",
        "latitude": 4.8450,
        "longitude": 7.0600,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "MRS Oil Port Harcourt Eleme Junction (Demo)",
        "brand": "MRS",
        "address": "Eleme Junction, Port Harcourt",
        "city": "Port Harcourt",
        "state": "Rivers",
        "latitude": 4.7550,
        "longitude": 7.0700,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },

    # ---- Bayelsa (Yenagoa) ----
    {
        "name": "NNPC Retail Yenagoa (Demo)",
        "brand": "NNPC",
        "address": "Yenagoa, Bayelsa",
        "city": "Yenagoa",
        "state": "Bayelsa",
        "latitude": 4.9267,
        "longitude": 6.2676,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "TotalEnergies Yenagoa Kpansia (Demo)",
        "brand": "TotalEnergies",
        "address": "Kpansia, Yenagoa",
        "city": "Yenagoa",
        "state": "Bayelsa",
        "latitude": 4.9400,
        "longitude": 6.2800,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Mobil Ogbia (Demo)",
        "brand": "Mobil",
        "address": "Ogbia Town, Bayelsa",
        "city": "Ogbia",
        "state": "Bayelsa",
        "latitude": 4.7833,
        "longitude": 6.3500,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Delta (Warri, Asaba) ----
    {
        "name": "NNPC Retail Warri Effurun (Demo)",
        "brand": "NNPC",
        "address": "Effurun, Warri",
        "city": "Warri",
        "state": "Delta",
        "latitude": 5.5547,
        "longitude": 5.7934,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Warri NPA (Demo)",
        "brand": "TotalEnergies",
        "address": "NPA Expressway, Warri",
        "city": "Warri",
        "state": "Delta",
        "latitude": 5.5400,
        "longitude": 5.7700,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Warri Airport Road (Demo)",
        "brand": "Mobil",
        "address": "Airport Road, Warri",
        "city": "Warri",
        "state": "Delta",
        "latitude": 5.5700,
        "longitude": 5.8100,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Asaba (Demo)",
        "brand": "Conoil",
        "address": "Asaba, Delta",
        "city": "Asaba",
        "state": "Delta",
        "latitude": 6.1986,
        "longitude": 6.7100,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Oando Asaba Summit (Demo)",
        "brand": "Oando",
        "address": "Summit Road, Asaba",
        "city": "Asaba",
        "state": "Delta",
        "latitude": 6.2150,
        "longitude": 6.7250,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "NNPC Retail Agbor (Demo)",
        "brand": "NNPC",
        "address": "Agbor, Delta",
        "city": "Agbor",
        "state": "Delta",
        "latitude": 6.2519,
        "longitude": 6.1940,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "TotalEnergies Ughelli (Demo)",
        "brand": "TotalEnergies",
        "address": "Ughelli, Delta",
        "city": "Ughelli",
        "state": "Delta",
        "latitude": 5.5083,
        "longitude": 5.9961,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Edo (Benin City) ----
    {
        "name": "NNPC Retail Benin City Ring Road (Demo)",
        "brand": "NNPC",
        "address": "Ring Road, Benin City",
        "city": "Benin City",
        "state": "Edo",
        "latitude": 6.3350,
        "longitude": 5.6037,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Benin City Sapele Road (Demo)",
        "brand": "TotalEnergies",
        "address": "Sapele Road, Benin City",
        "city": "Benin City",
        "state": "Edo",
        "latitude": 6.3000,
        "longitude": 5.6300,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Benin City GRA (Demo)",
        "brand": "Mobil",
        "address": "GRA, Benin City",
        "city": "Benin City",
        "state": "Edo",
        "latitude": 6.3400,
        "longitude": 5.6200,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Benin City Airport Road (Demo)",
        "brand": "Conoil",
        "address": "Airport Road, Benin City",
        "city": "Benin City",
        "state": "Edo",
        "latitude": 6.3200,
        "longitude": 5.5950,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Oando Auchi (Demo)",
        "brand": "Oando",
        "address": "Auchi, Edo",
        "city": "Auchi",
        "state": "Edo",
        "latitude": 7.0667,
        "longitude": 6.2667,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Cross River (Calabar) ----
    {
        "name": "NNPC Retail Calabar Marian (Demo)",
        "brand": "NNPC",
        "address": "Marian Road, Calabar",
        "city": "Calabar",
        "state": "Cross River",
        "latitude": 4.9580,
        "longitude": 8.3269,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Calabar Parliamentary (Demo)",
        "brand": "TotalEnergies",
        "address": "Parliamentary Road, Calabar",
        "city": "Calabar",
        "state": "Cross River",
        "latitude": 4.9700,
        "longitude": 8.3400,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Calabar IBB Way (Demo)",
        "brand": "Mobil",
        "address": "IBB Way, Calabar",
        "city": "Calabar",
        "state": "Cross River",
        "latitude": 4.9500,
        "longitude": 8.3150,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Ogoja (Demo)",
        "brand": "Conoil",
        "address": "Ogoja, Cross River",
        "city": "Ogoja",
        "state": "Cross River",
        "latitude": 6.6583,
        "longitude": 8.7972,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },

    # ---- Akwa Ibom (Uyo, Eket) ----
    {
        "name": "NNPC Retail Uyo Akpan Andem (Demo)",
        "brand": "NNPC",
        "address": "Akpan Andem, Uyo",
        "city": "Uyo",
        "state": "Akwa Ibom",
        "latitude": 5.0380,
        "longitude": 7.9100,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG", "CNG"],
    },
    {
        "name": "TotalEnergies Uyo Wellington Bassey (Demo)",
        "brand": "TotalEnergies",
        "address": "Wellington Bassey Way, Uyo",
        "city": "Uyo",
        "state": "Akwa Ibom",
        "latitude": 5.0500,
        "longitude": 7.9200,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
    {
        "name": "Mobil Uyo Nwaniba (Demo)",
        "brand": "Mobil",
        "address": "Nwaniba Road, Uyo",
        "city": "Uyo",
        "state": "Akwa Ibom",
        "latitude": 5.0250,
        "longitude": 7.9400,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Conoil Eket (Demo)",
        "brand": "Conoil",
        "address": "Eket, Akwa Ibom",
        "city": "Eket",
        "state": "Akwa Ibom",
        "latitude": 4.6500,
        "longitude": 7.9200,
        "fuel_types": ["PMS", "AGO", "DPK"],
    },
    {
        "name": "Oando Ikot Ekpene (Demo)",
        "brand": "Oando",
        "address": "Ikot Ekpene, Akwa Ibom",
        "city": "Ikot Ekpene",
        "state": "Akwa Ibom",
        "latitude": 5.1810,
        "longitude": 7.7150,
        "fuel_types": ["PMS", "AGO", "DPK", "LPG"],
    },
]
